---
driver:
  name: vagrant
  gui: false
  synced_folders:
    - ["synced_folder", "C:\\synced_folder"]

provisioner:
  name: shell # calls bootstrap.ps1 script to install the package

verifier:
  name: inspec

platforms:
  - name: windows-2012-r2
    driver:
      box: mwrock/Windows2012R2
    run_list:
      - recipe[test_msi_installer]

suites:
  - name: default
