---
driver:
  name: vagrant
  gui: false
  # Optionally save the `.msi` to ./synced_folder/package.msi and share the
  # folder onto the VMs:
  # synced_folders:
  #   - ["synced_folder", "C:\\synced_folder"]

provisioner:
  name: shell # calls bootstrap.ps1 script to install the package

verifier:
  name: inspec

platforms:
  - name: windows-2012-r2
    driver:
      box: mwrock/Windows2012R2
  - name: windows-2016
    driver:
      box: mwrock/Windows2016
  # Might be able to upgrade powershell on nano to support this, (nano is very
  # slimmed down) and would be ideal for test instances
  # https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-windows#deploying-on-nano-server
  # https://github.com/PowerShell/PowerShell/releases/download/v6.0.2/PowerShell-6.0.2-win-x64.msi
  # - name: windows-nano
  #   driver:
  #     box: mwrock/WindowsNano

suites:
  - name: default
